name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Deploy applications
        run: |
          cd ~/docker-app-deployment
          ./deploy.sh
